##LOAD HE DATASET

In [1]:
import pandas as  pd
data=pd.read_csv('/content/STEG_BILLING_HISTORY(1).csv')

#Import the neesary llibraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#EDA

In [5]:
data.types

client_id                object
invoice_date             object
tarif_type                int64
counter_number          float64
counter_statue          float64
counter_code            float64
reading_remarque        float64
counter_coefficient     float64
consommation_level_1    float64
consommation_level_2    float64
consommation_level_3    float64
consommation_level_4    float64
old_index               float64
new_index               float64
months_number           float64
counter_type             object
dtype: object

In [6]:
data.head()

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11,1335667.0,0.0,203.0,8.0,1.0,82.0,0.0,0.0,0.0,14302.0,14384.0,4.0,ELEC
1,train_Client_0,2013-03-29,11,1335667.0,0.0,203.0,6.0,1.0,1200.0,184.0,0.0,0.0,12294.0,13678.0,4.0,ELEC
2,train_Client_0,2015-03-23,11,1335667.0,0.0,203.0,8.0,1.0,123.0,0.0,0.0,0.0,14624.0,14747.0,4.0,ELEC
3,train_Client_0,2015-07-13,11,1335667.0,0.0,207.0,8.0,1.0,102.0,0.0,0.0,0.0,14747.0,14849.0,4.0,ELEC
4,train_Client_0,2016-11-17,11,1335667.0,0.0,207.0,9.0,1.0,572.0,0.0,0.0,0.0,15066.0,15638.0,12.0,ELEC

In [7]:
data.tail()

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
90187,train_Client_102417,2008-05-29,11,158346.0,0.0,203.0,6.0,1.0,1167.0,0.0,0.0,0.0,9901.0,11068.0,4.0,ELEC
90188,train_Client_102417,2008-01-31,40,6709462.0,0.0,5.0,6.0,1.0,1169.0,0.0,0.0,0.0,4179.0,5348.0,4.0,GAZ
90189,train_Client_102417,2008-01-31,11,158346.0,0.0,203.0,6.0,1.0,1200.0,63.0,0.0,0.0,8638.0,9901.0,4.0,ELEC
90190,train_Client_102417,2007-09-21,40,6709462.0,0.0,5.0,6.0,1.0,165.0,0.0,0.0,0.0,4014.0,4179.0,4.0,GAZ
90191,train_Client_102417,2010-01-02,11,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
data.columns

Index(['client_id', 'invoice_date', 'tarif_type', 'counter_number',
       'counter_statue', 'counter_code', 'reading_remarque',
       'counter_coefficient', 'consommation_level_1', 'consommation_level_2',
       'consommation_level_3', 'consommation_level_4', 'old_index',
       'new_index', 'months_number', 'counter_type'],
      dtype='object')

#Checking the missing values

In [10]:
data.isnull().sum()

client_id                0
invoice_date             0
tarif_type               0
counter_number           2
counter_statue           1
counter_code             1
reading_remarque        83
counter_coefficient      1
consommation_level_1     1
consommation_level_2     1
consommation_level_3     1
consommation_level_4     1
old_index                1
new_index                1
months_number            1
counter_type             1
dtype: int64

Handling the missing values

In [14]:
# Drop irrelevant or heavily missing columns if they exist
cols_to_drop = ['counter_statue', 'reading_remarque']
data.drop(columns=[col for col in cols_to_drop if col in data.columns], inplace=True)

# Fill categorical columns with mode
cat_cols = ['counter_code', 'counter_type', 'counter_number']
for col in cat_cols:
    if col in data.columns: # Check if column exists before filling
        data[col] = data[col].fillna(data[col].mode()[0])

# Fill numeric columns with mean
num_cols = ['counter_coefficient', 'consommation_level_1', 'consommation_level_2',
            'consommation_level_3', 'consommation_level_4', 'old_index',
            'new_index', 'months_number']
for col in num_cols:
    if col in data.columns: # Check if column exists before filling
        data[col] = data[col].fillna(data[col].mean())

#Confirming missig vakes

#Handling duplicates

In [16]:
data.duplicated().sum()

np.int64(0)

#Handling ouliers

In [24]:
# List of numeric columns
numeric_cols = [
    'counter_coefficient', 'consommation_level_1', 'consommation_level_2',
    'consommation_level_3', 'consommation_level_4',
    'old_index', 'new_index', 'months_number'
]

# Loop through each numeric column to handle outliers
for col in numeric_cols:
    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Replace outliers with NaN
    data[col] = data[col].apply(lambda x: x if lower_bound <= x <= upper_bound else None)

    # Optionally fill NaN with median
    data[col] = data[col].fillna(data[col].median())

#Encoding

In [20]:
data.describe(include='object')

                  client_id invoice_date counter_type
count                 90192        90192        90192
unique                 2691         3656            2
top     train_Client_101645   2010-04-10         ELEC
freq                    254           77        61978

#Encodng

In [22]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
data['counter_type_encoded'] = le.fit_transform(data['counter_type'])

In [23]:
data.drop(columns=['counter_statue'], inplace=True)

KeyError: "['counter_statue'] not found in axis"

# Convert 'invoice_date' to datetime objects

In [25]:
data['invoice_date'] = pd.to_datetime(data['invoice_date'])
display(data['invoice_date'].head())

0   2014-03-24
1   2013-03-29
2   2015-03-23
3   2015-07-13
4   2016-11-17
Name: invoice_date, dtype: datetime64[ns]